name: "🐛 Bug Report"
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, please tell us what you expected to happen. Please convert .gpx files to .txt and attach them when appropriate.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of wanderer are you running?
      placeholder: ex. v0.17.2
    validations:
      required: true