name: "💡 Feature request"
description: Suggest an idea for this project.
labels: ["feature request"]
body:
  - type: textarea
    id: what-would-you-like
    attributes:
        label: What would you like to see?
        description: Describe the feature you'd like to see added to wanderer.
        placeholder: "I would love to see..."
    validations:
        required: true
