name: Build Documentation
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm install
        working-directory: docs
      - name: Build docs
        run: npm run build
        working-directory: docs

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          platforms: linux/amd64,linux/arm64
          context: docs
          push: true
          tags: flomp/wanderer-docs:latest
